# Generated by Django 4.2.2 on 2024-04-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_palette_user_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
